name: Jmeter Test Workflow
on: [push]
jobs:
  jmeter_tests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Download and Extract JMeter
        run: |
          Invoke-WebRequest -Uri https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.5.zip -OutFile apache-jmeter-5.5.zip
          Expand-Archive -Path apache-jmeter-5.5.zip -DestinationPath .

      - name: Download and Install JMeter Plugins Manager
        run: |
          Invoke-WebRequest -Uri https://jmeter-plugins.org/get/ -OutFile .\apache-jmeter-5.5\lib\ext\jmeter-plugins-manager.jar
          java -cp .\apache-jmeter-5.5\lib\ext\jmeter-plugins-manager.jar org.jmeterplugins.repository.PluginManagerCMDInstaller

      - name: Run JMeter tests
        run: .\apache-jmeter-5.5\bin\jmeter.bat -n -t ForgeAPI_v3.jmx -l Forgeresults.jtl

      - name: Print JTL File
        run: |
          cat .\apache-jmeter-5.5\bin\Forgeresults.jtl

      - name: Generate Report
        run: .\apache-jmeter-5.5\bin\jmeter.bat -g Forgeresults.jtl -o ./report
